stages:
  - build
  - deploy

build_demo:
  stage: build
  image: maven:latest
  script:
    - mvn package
  artifacts:
    paths:
      - target/demo.war

deploy_web_terminal:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    CONTAINER_NAME: web-terminal
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker run -d --name $CONTAINER_NAME -p 8080:8080 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master
